"""
Homework models with AI integration support.

This module provides models for homework assignments that can be:
1. Manually created by teachers
2. Auto-generated by AI based on paragraphs
3. Auto-graded by AI for open-ended questions
"""
from sqlalchemy import (
    Column, String, Integer, ForeignKey, Text, DateTime, Boolean,
    Enum as SQLEnum, Float, Index, UniqueConstraint, CheckConstraint
)
from sqlalchemy.dialects.postgresql import JSONB, ARRAY
from sqlalchemy.orm import relationship
from datetime import datetime
import enum

from app.models.base import SoftDeleteModel, BaseModel
from app.core.database import Base


# ============================================================================
# ENUMS
# ============================================================================

class HomeworkStatus(str, enum.Enum):
    """Homework lifecycle status."""
    DRAFT = "draft"
    PUBLISHED = "published"
    CLOSED = "closed"
    ARCHIVED = "archived"


class HomeworkTaskType(str, enum.Enum):
    """Type of homework task."""
    READ = "read"                    # Read a paragraph
    QUIZ = "quiz"                    # Multiple choice / true-false
    OPEN_QUESTION = "open_question"  # Short answer, AI can grade
    ESSAY = "essay"                  # Long form, AI grades with rubric
    PRACTICE = "practice"            # Practice problems
    CODE = "code"                    # Code submission


class HomeworkQuestionType(str, enum.Enum):
    """Type of homework question."""
    SINGLE_CHOICE = "single_choice"
    MULTIPLE_CHOICE = "multiple_choice"
    TRUE_FALSE = "true_false"
    SHORT_ANSWER = "short_answer"
    OPEN_ENDED = "open_ended"
    CODE = "code"


class HomeworkStudentStatus(str, enum.Enum):
    """Student homework completion status."""
    ASSIGNED = "assigned"
    IN_PROGRESS = "in_progress"
    SUBMITTED = "submitted"
    GRADED = "graded"
    RETURNED = "returned"


class TaskSubmissionStatus(str, enum.Enum):
    """Individual task submission status."""
    NOT_STARTED = "not_started"
    IN_PROGRESS = "in_progress"
    SUBMITTED = "submitted"
    NEEDS_REVIEW = "needs_review"  # Requires manual teacher review
    GRADED = "graded"


class BloomLevel(str, enum.Enum):
    """Bloom's Taxonomy cognitive levels."""
    REMEMBER = "remember"
    UNDERSTAND = "understand"
    APPLY = "apply"
    ANALYZE = "analyze"
    EVALUATE = "evaluate"
    CREATE = "create"


class AIOperationType(str, enum.Enum):
    """Type of AI operation for logging."""
    QUESTION_GENERATION = "question_generation"
    ANSWER_GRADING = "answer_grading"
    FEEDBACK_GENERATION = "feedback_generation"
    PERSONALIZATION = "personalization"


# ============================================================================
# MAIN MODELS
# ============================================================================

class Homework(SoftDeleteModel):
    """
    Homework assignment created by teacher for a class.

    Can contain multiple tasks based on different paragraphs.
    Supports AI generation and personalization.
    """
    __tablename__ = "homework"

    # ---- Relationships ----
    school_id = Column(
        Integer,
        ForeignKey("schools.id", ondelete="CASCADE"),
        nullable=False,
        index=True
    )
    class_id = Column(
        Integer,
        ForeignKey("school_classes.id", ondelete="CASCADE"),
        nullable=False,
        index=True
    )
    teacher_id = Column(
        Integer,
        ForeignKey("teachers.id", ondelete="CASCADE"),
        nullable=False,
        index=True
    )

    # ---- Basic Info ----
    title = Column(String(255), nullable=False)
    description = Column(Text, nullable=True)

    # ---- Time Management ----
    assigned_at = Column(DateTime(timezone=True), server_default="now()", nullable=False)
    due_date = Column(DateTime(timezone=True), nullable=False, index=True)
    late_submission_allowed = Column(Boolean, default=False, nullable=False)
    late_penalty_per_day = Column(Integer, default=0, nullable=False)  # процент штрафа за день
    grace_period_hours = Column(Integer, default=0, nullable=False)  # льготный период без штрафа
    max_late_days = Column(Integer, default=7, nullable=False)  # максимум дней опоздания

    # ---- AI Settings ----
    ai_generation_enabled = Column(Boolean, default=False, nullable=False)
    target_difficulty = Column(String(20), default="auto", nullable=False)  # easy/medium/hard/auto
    personalization_enabled = Column(Boolean, default=True, nullable=False)

    # ---- Grading Settings ----
    auto_check_enabled = Column(Boolean, default=True, nullable=False)  # Auto-check closed questions
    ai_check_enabled = Column(Boolean, default=False, nullable=False)   # AI grades open questions
    show_answers_after = Column(String(20), default="submission", nullable=False)  # submission/deadline/manual
    show_explanations = Column(Boolean, default=True, nullable=False)

    # ---- Status ----
    status = Column(
        SQLEnum(
            HomeworkStatus,
            name="homework_status_enum",
            create_type=True,
            values_callable=lambda obj: [e.value for e in obj]  # Use lowercase values
        ),
        nullable=False,
        default=HomeworkStatus.DRAFT,
        index=True
    )
    is_active = Column(Boolean, default=True, nullable=False)

    # ---- Relationships ----
    school = relationship("School", backref="homework_assignments")
    school_class = relationship("SchoolClass", backref="homework_assignments")
    teacher = relationship("Teacher", backref="homework_created")
    tasks = relationship("HomeworkTask", back_populates="homework", cascade="all, delete-orphan")
    student_homework = relationship("HomeworkStudent", back_populates="homework", cascade="all, delete-orphan")

    __table_args__ = (
        Index("idx_homework_school_class", "school_id", "class_id"),
        Index("idx_homework_due_date_status", "due_date", "status"),
        CheckConstraint("late_penalty_per_day >= 0 AND late_penalty_per_day <= 100", name="ck_late_penalty_range"),
        CheckConstraint("grace_period_hours >= 0 AND grace_period_hours <= 168", name="ck_grace_period_range"),  # до 7 дней
        CheckConstraint("max_late_days >= 0 AND max_late_days <= 30", name="ck_max_late_days_range"),
    )

    def __repr__(self) -> str:
        return f"<Homework(id={self.id}, title='{self.title}', status={self.status})>"


class HomeworkTask(SoftDeleteModel):
    """
    Individual task within a homework assignment.

    Links to a paragraph and can contain AI-generated or static questions.
    """
    __tablename__ = "homework_tasks"

    homework_id = Column(
        Integer,
        ForeignKey("homework.id", ondelete="CASCADE"),
        nullable=False,
        index=True
    )

    # ---- Денормализация для RLS без JOIN (v2) ----
    school_id = Column(
        Integer,
        ForeignKey("schools.id", ondelete="CASCADE"),
        nullable=False,
        index=True
    )

    # ---- Content Links ----
    paragraph_id = Column(Integer, ForeignKey("paragraphs.id", ondelete="SET NULL"), nullable=True, index=True)
    chapter_id = Column(Integer, ForeignKey("chapters.id", ondelete="SET NULL"), nullable=True, index=True)
    learning_outcome_id = Column(Integer, ForeignKey("learning_outcomes.id", ondelete="SET NULL"), nullable=True)

    # ---- Task Configuration ----
    task_type = Column(
        SQLEnum(
            HomeworkTaskType,
            name="homework_task_type_enum",
            create_type=True,
            values_callable=lambda obj: [e.value for e in obj]
        ),
        nullable=False
    )
    sort_order = Column(Integer, default=0, nullable=False)
    is_required = Column(Boolean, default=True, nullable=False)
    points = Column(Integer, default=10, nullable=False)
    time_limit_minutes = Column(Integer, nullable=True)
    max_attempts = Column(Integer, default=1, nullable=False)  # ограничение попыток (v2)

    # ---- AI Generation ----
    ai_generated = Column(Boolean, default=False, nullable=False)
    ai_prompt_template = Column(Text, nullable=True)
    generation_params = Column(JSONB, default={}, nullable=False)
    # Example generation_params:
    # {
    #   "questions_count": 5,
    #   "question_types": ["single_choice", "short_answer"],
    #   "bloom_levels": ["understand", "apply"],
    #   "language": "ru"
    # }

    # ---- Static Content ----
    static_content = Column(Text, nullable=True)
    static_question_ids = Column(ARRAY(Integer), nullable=True)  # Reference existing questions

    # ---- Instructions ----
    instructions = Column(Text, nullable=True)

    # ---- Relationships ----
    homework = relationship("Homework", back_populates="tasks")
    school = relationship("School", backref="homework_tasks")
    paragraph = relationship("Paragraph", backref="homework_tasks")
    chapter = relationship("Chapter", backref="homework_tasks")
    learning_outcome = relationship("LearningOutcome", backref="homework_tasks")
    questions = relationship("HomeworkTaskQuestion", back_populates="task", cascade="all, delete-orphan")
    submissions = relationship("StudentTaskSubmission", back_populates="task", cascade="all, delete-orphan")

    __table_args__ = (
        Index("idx_homework_task_paragraph", "paragraph_id"),
        Index("idx_homework_task_homework", "homework_id", "sort_order"),
        Index("idx_homework_task_school", "school_id"),
        CheckConstraint("max_attempts >= 1 AND max_attempts <= 10", name="ck_max_attempts_range"),
    )

    def __repr__(self) -> str:
        return f"<HomeworkTask(id={self.id}, type={self.task_type}, homework_id={self.homework_id})>"


class HomeworkTaskQuestion(SoftDeleteModel):
    """
    Question within a homework task.

    Can be AI-generated or manually created.
    Supports both closed (auto-graded) and open (AI-graded) questions.
    """
    __tablename__ = "homework_task_questions"

    homework_task_id = Column(
        Integer,
        ForeignKey("homework_tasks.id", ondelete="CASCADE"),
        nullable=False,
        index=True
    )

    # ---- Denormalized for RLS (v3) ----
    school_id = Column(
        Integer,
        ForeignKey("schools.id", ondelete="CASCADE"),
        nullable=False,
        index=True
    )

    # ---- Question Content ----
    question_type = Column(
        SQLEnum(
            HomeworkQuestionType,
            name="homework_question_type_enum",
            create_type=True,
            values_callable=lambda obj: [e.value for e in obj]
        ),
        nullable=False
    )
    question_text = Column(Text, nullable=False)
    question_html = Column(Text, nullable=True)  # Formatted (LaTeX, code highlighting)

    # ---- Answer Options (for closed questions) ----
    options = Column(JSONB, nullable=True)
    # Example: [{"id": "a", "text": "Option A", "is_correct": true}, ...]
    correct_answer = Column(Text, nullable=True)  # For short_answer
    answer_pattern = Column(String(500), nullable=True)  # Regex for validation

    # ---- AI Grading (for open questions) ----
    grading_rubric = Column(JSONB, nullable=True)
    # Example:
    # {
    #   "criteria": [
    #     {"name": "Understanding", "weight": 0.4, "levels": ["excellent", "good", "partial", "none"]},
    #     {"name": "Argumentation", "weight": 0.3, ...}
    #   ],
    #   "max_score": 10
    # }
    expected_answer_hints = Column(Text, nullable=True)
    ai_grading_prompt = Column(Text, nullable=True)

    # ---- Metadata ----
    points = Column(Integer, default=1, nullable=False)
    sort_order = Column(Integer, default=0, nullable=False)
    difficulty = Column(String(20), nullable=True)  # easy/medium/hard
    bloom_level = Column(
        SQLEnum(
            BloomLevel,
            name="bloom_level_enum",
            create_type=True,
            values_callable=lambda obj: [e.value for e in obj]
        ),
        nullable=True
    )
    explanation = Column(Text, nullable=True)

    # ---- AI Generation Metadata ----
    ai_generated = Column(Boolean, default=False, nullable=False)
    generation_model = Column(String(100), nullable=True)
    generation_metadata = Column(JSONB, nullable=True)

    # ---- Версионирование (v2) ----
    version = Column(Integer, default=1, nullable=False)
    is_active = Column(Boolean, default=True, nullable=False)  # активная версия
    replaced_by_id = Column(Integer, ForeignKey("homework_task_questions.id", ondelete="SET NULL"), nullable=True)

    # ---- Relationships ----
    task = relationship("HomeworkTask", back_populates="questions")
    school = relationship("School", backref="homework_task_questions")
    answers = relationship("StudentTaskAnswer", back_populates="question", cascade="all, delete-orphan")
    replaced_by = relationship("HomeworkTaskQuestion", remote_side="HomeworkTaskQuestion.id", uselist=False)

    __table_args__ = (
        Index("idx_homework_question_task", "homework_task_id", "sort_order"),
        Index("idx_questions_active_version", "homework_task_id", "is_active", "version"),
        Index("idx_homework_task_questions_school", "school_id"),
    )

    def __repr__(self) -> str:
        return f"<HomeworkTaskQuestion(id={self.id}, type={self.question_type})>"


class HomeworkStudent(SoftDeleteModel):
    """
    Assignment of homework to a specific student.

    Tracks personalization settings and overall progress.
    """
    __tablename__ = "homework_students"

    homework_id = Column(
        Integer,
        ForeignKey("homework.id", ondelete="CASCADE"),
        nullable=False,
        index=True
    )
    student_id = Column(
        Integer,
        ForeignKey("students.id", ondelete="CASCADE"),
        nullable=False,
        index=True
    )
    school_id = Column(
        Integer,
        ForeignKey("schools.id", ondelete="CASCADE"),
        nullable=False,
        index=True
    )

    # ---- Personalization ----
    assigned_difficulty = Column(String(20), nullable=True)  # Personalized difficulty at assignment
    mastery_level_at_assign = Column(String(1), nullable=True)  # A/B/C at assignment time
    personalized_task_ids = Column(ARRAY(Integer), nullable=True)  # Which tasks assigned

    # ---- Status ----
    status = Column(
        SQLEnum(
            HomeworkStudentStatus,
            name="homework_student_status_enum",
            create_type=True,
            values_callable=lambda obj: [e.value for e in obj]
        ),
        nullable=False,
        default=HomeworkStudentStatus.ASSIGNED,
        index=True
    )

    # ---- Timestamps ----
    assigned_at = Column(DateTime(timezone=True), server_default="now()", nullable=False)
    started_at = Column(DateTime(timezone=True), nullable=True)
    submitted_at = Column(DateTime(timezone=True), nullable=True)
    graded_at = Column(DateTime(timezone=True), nullable=True)

    # ---- Results ----
    total_score = Column(Float, nullable=True)
    max_score = Column(Float, nullable=True)
    percentage = Column(Float, nullable=True)
    time_spent_seconds = Column(Integer, default=0, nullable=False)

    # ---- AI Grading ----
    ai_graded = Column(Boolean, default=False, nullable=False)
    ai_feedback = Column(Text, nullable=True)
    teacher_reviewed = Column(Boolean, default=False, nullable=False)
    teacher_adjusted_score = Column(Float, nullable=True)
    teacher_feedback = Column(Text, nullable=True)

    # ---- Additional ----
    submission_count = Column(Integer, default=0, nullable=False)
    late_submitted = Column(Boolean, default=False, nullable=False)

    # ---- Relationships ----
    homework = relationship("Homework", back_populates="student_homework")
    student = relationship("Student", backref="homework_assignments")
    task_submissions = relationship("StudentTaskSubmission", back_populates="homework_student", cascade="all, delete-orphan")

    __table_args__ = (
        UniqueConstraint("homework_id", "student_id", name="uq_homework_student"),
        Index("idx_homework_student_school", "school_id", "student_id"),
        Index("idx_homework_student_status", "status"),
    )

    def __repr__(self) -> str:
        return f"<HomeworkStudent(homework_id={self.homework_id}, student_id={self.student_id}, status={self.status})>"


class StudentTaskSubmission(SoftDeleteModel):
    """
    Student's submission for a specific task.

    Tracks progress and scores for individual tasks.
    """
    __tablename__ = "student_task_submissions"

    homework_student_id = Column(
        Integer,
        ForeignKey("homework_students.id", ondelete="CASCADE"),
        nullable=False,
        index=True
    )
    homework_task_id = Column(
        Integer,
        ForeignKey("homework_tasks.id", ondelete="CASCADE"),
        nullable=False,
        index=True
    )
    student_id = Column(
        Integer,
        ForeignKey("students.id", ondelete="CASCADE"),
        nullable=False,
        index=True
    )
    school_id = Column(
        Integer,
        ForeignKey("schools.id", ondelete="CASCADE"),
        nullable=False,
        index=True
    )

    # ---- Status ----
    status = Column(
        SQLEnum(
            TaskSubmissionStatus,
            name="task_submission_status_enum",
            create_type=True,
            values_callable=lambda obj: [e.value for e in obj]
        ),
        nullable=False,
        default=TaskSubmissionStatus.NOT_STARTED
    )

    # ---- Results ----
    score = Column(Float, nullable=True)
    max_score = Column(Float, nullable=True)
    time_spent_seconds = Column(Integer, default=0, nullable=False)

    # ---- AI Grading ----
    ai_score = Column(Float, nullable=True)
    ai_confidence = Column(Float, nullable=True)  # 0.0-1.0
    ai_feedback = Column(Text, nullable=True)
    ai_graded_at = Column(DateTime(timezone=True), nullable=True)

    # ---- Timestamps ----
    started_at = Column(DateTime(timezone=True), nullable=True)
    submitted_at = Column(DateTime(timezone=True), nullable=True)
    attempt_number = Column(Integer, default=1, nullable=False)

    # ---- Late Submission Tracking (v2) ----
    is_late = Column(Boolean, default=False, nullable=False)
    late_penalty_applied = Column(Float, default=0, nullable=False)  # процент штрафа (0-100)
    original_score = Column(Float, nullable=True)  # оценка до штрафа

    # ---- Relationships ----
    homework_student = relationship("HomeworkStudent", back_populates="task_submissions")
    task = relationship("HomeworkTask", back_populates="submissions")
    student = relationship("Student", backref="task_submissions")
    answers = relationship("StudentTaskAnswer", back_populates="submission", cascade="all, delete-orphan")

    __table_args__ = (
        UniqueConstraint("homework_student_id", "homework_task_id", "attempt_number", name="uq_task_submission_attempt"),
        Index("idx_task_submission_student", "student_id", "school_id"),
        CheckConstraint("late_penalty_applied >= 0 AND late_penalty_applied <= 100", name="ck_late_penalty_applied_range"),
    )

    def __repr__(self) -> str:
        return f"<StudentTaskSubmission(id={self.id}, task_id={self.homework_task_id}, status={self.status})>"


class StudentTaskAnswer(SoftDeleteModel):
    """
    Individual answer to a question.

    Stores the student's response and grading results (auto or AI).
    """
    __tablename__ = "student_task_answers"

    submission_id = Column(
        Integer,
        ForeignKey("student_task_submissions.id", ondelete="CASCADE"),
        nullable=False,
        index=True
    )
    question_id = Column(
        Integer,
        ForeignKey("homework_task_questions.id", ondelete="CASCADE"),
        nullable=False,
        index=True
    )
    student_id = Column(
        Integer,
        ForeignKey("students.id", ondelete="CASCADE"),
        nullable=False,
        index=True
    )
    school_id = Column(
        Integer,
        ForeignKey("schools.id", ondelete="CASCADE"),
        nullable=False,
        index=True
    )

    # ---- Answer Content ----
    answer_type = Column(String(30), nullable=True)  # selected_option/text/code/file
    selected_option_ids = Column(JSONB, nullable=True)  # ["a", "c"] for multiple choice
    answer_text = Column(Text, nullable=True)
    answer_code = Column(Text, nullable=True)
    answer_file_url = Column(String(500), nullable=True)

    # ---- Auto-grading (closed questions) ----
    is_correct = Column(Boolean, nullable=True)
    partial_score = Column(Float, nullable=True)  # 0.0-1.0

    # ---- AI Grading (open questions) ----
    ai_score = Column(Float, nullable=True)
    ai_confidence = Column(Float, nullable=True)  # 0.0-1.0
    ai_feedback = Column(Text, nullable=True)
    ai_rubric_scores = Column(JSONB, nullable=True)
    # Example:
    # {
    #   "criteria_scores": [
    #     {"name": "Understanding", "score": 8, "max": 10, "comment": "Good understanding..."}
    #   ],
    #   "total": 8, "max_total": 10
    # }
    ai_grading_model = Column(String(100), nullable=True)
    ai_graded_at = Column(DateTime(timezone=True), nullable=True)

    # ---- Teacher Override ----
    teacher_override_score = Column(Float, nullable=True)
    teacher_comment = Column(Text, nullable=True)
    flagged_for_review = Column(Boolean, default=False, nullable=False)

    # ---- Metadata ----
    answered_at = Column(DateTime(timezone=True), server_default="now()", nullable=False)
    time_spent_seconds = Column(Integer, nullable=True)

    # ---- Relationships ----
    submission = relationship("StudentTaskSubmission", back_populates="answers")
    question = relationship("HomeworkTaskQuestion", back_populates="answers")
    student = relationship("Student", backref="task_answers")

    __table_args__ = (
        UniqueConstraint("submission_id", "question_id", name="uq_answer_submission_question"),
        Index("idx_answer_flagged", "flagged_for_review", postgresql_where="flagged_for_review = true"),
        Index("idx_answer_student", "student_id", "school_id"),
    )

    def __repr__(self) -> str:
        return f"<StudentTaskAnswer(id={self.id}, question_id={self.question_id})>"


class AIGenerationLog(BaseModel):
    """
    Log of AI operations for auditing and model improvement.

    Records all AI generations and gradings for analysis.
    """
    __tablename__ = "ai_generation_logs"

    # ---- Context ----
    school_id = Column(Integer, ForeignKey("schools.id", ondelete="SET NULL"), nullable=True, index=True)
    teacher_id = Column(Integer, ForeignKey("teachers.id", ondelete="SET NULL"), nullable=True)
    homework_id = Column(Integer, ForeignKey("homework.id", ondelete="SET NULL"), nullable=True)
    homework_task_id = Column(Integer, ForeignKey("homework_tasks.id", ondelete="SET NULL"), nullable=True)
    student_id = Column(Integer, ForeignKey("students.id", ondelete="SET NULL"), nullable=True)

    # ---- Operation ----
    operation_type = Column(
        SQLEnum(
            AIOperationType,
            name="ai_operation_type_enum",
            create_type=True,
            values_callable=lambda obj: [e.value for e in obj]
        ),
        nullable=False,
        index=True
    )

    # ---- Input ----
    input_context = Column(JSONB, nullable=True)
    prompt_used = Column(Text, nullable=True)

    # ---- Output ----
    model_used = Column(String(100), nullable=True)
    raw_response = Column(Text, nullable=True)
    parsed_output = Column(JSONB, nullable=True)

    # ---- Metrics ----
    tokens_input = Column(Integer, nullable=True)
    tokens_output = Column(Integer, nullable=True)
    latency_ms = Column(Integer, nullable=True)
    cost_usd = Column(Float, nullable=True)

    # ---- Quality ----
    success = Column(Boolean, default=True, nullable=False)
    error_message = Column(Text, nullable=True)
    human_rating = Column(Integer, nullable=True)  # 1-5 teacher rating
    human_feedback = Column(Text, nullable=True)

    # ---- Relationships ----
    school = relationship("School", backref="ai_logs")
    teacher = relationship("Teacher", backref="ai_logs")
    homework = relationship("Homework", backref="ai_logs")
    task = relationship("HomeworkTask", backref="ai_logs")
    student = relationship("Student", backref="ai_logs")

    __table_args__ = (
        Index("idx_ai_log_operation_date", "operation_type", "created_at"),
        Index("idx_ai_log_school", "school_id", "created_at"),
        CheckConstraint("human_rating IS NULL OR (human_rating >= 1 AND human_rating <= 5)", name="ck_human_rating_range"),
    )

    def __repr__(self) -> str:
        return f"<AIGenerationLog(id={self.id}, type={self.operation_type})>"
