"""
Student memory models for AI chat personalization.

Two layers:
- ChatSessionSummary: LLM-generated summary per chat session
- StudentMemory: long-term learner profile (one row per student)
"""
from sqlalchemy import Column, String, Integer, ForeignKey, Text
from sqlalchemy.dialects.postgresql import JSONB

from app.models.base import BaseModel


class ChatSessionSummary(BaseModel):
    """Summary of a chat session, generated by LLM after conversation."""

    __tablename__ = "chat_session_summaries"

    session_id = Column(
        Integer,
        ForeignKey("chat_sessions.id", ondelete="CASCADE"),
        nullable=False,
        unique=True
    )
    student_id = Column(
        Integer,
        ForeignKey("students.id", ondelete="CASCADE"),
        nullable=False,
        index=True
    )
    school_id = Column(
        Integer,
        ForeignKey("schools.id", ondelete="CASCADE"),
        nullable=False,
        index=True
    )

    topic = Column(String(255), nullable=True)
    summary = Column(Text, nullable=False)
    knowledge_gaps = Column(JSONB, default=list)
    confidence_level = Column(String(20), nullable=True)
    message_count = Column(Integer, default=0)

    def __repr__(self) -> str:
        return f"<ChatSessionSummary(session={self.session_id}, topic='{self.topic}')>"


class StudentMemory(BaseModel):
    """Long-term learner profile, updated incrementally after conversations."""

    __tablename__ = "student_memory"

    student_id = Column(
        Integer,
        ForeignKey("students.id", ondelete="CASCADE"),
        nullable=False,
        unique=True,
        index=True
    )
    school_id = Column(
        Integer,
        ForeignKey("schools.id", ondelete="CASCADE"),
        nullable=False,
        index=True
    )

    memory_data = Column(JSONB, nullable=False, default=dict)
    extraction_count = Column(Integer, default=0, nullable=False)
    last_session_id = Column(
        Integer,
        ForeignKey("chat_sessions.id", ondelete="SET NULL"),
        nullable=True
    )

    def __repr__(self) -> str:
        return f"<StudentMemory(student={self.student_id}, extractions={self.extraction_count})>"
