"""
Teacher memory models for AI chat personalization.

Two layers:
- TeacherChatSessionSummary: LLM-generated summary per teacher chat session
- TeacherMemory: long-term teacher profile (one row per teacher)
"""
from sqlalchemy import Column, String, Integer, ForeignKey, Text
from sqlalchemy.dialects.postgresql import JSONB

from app.models.base import BaseModel


class TeacherChatSessionSummary(BaseModel):
    """Summary of a teacher chat session, generated by LLM after conversation."""

    __tablename__ = "teacher_chat_session_summaries"

    session_id = Column(
        Integer,
        ForeignKey("chat_sessions.id", ondelete="CASCADE"),
        nullable=False,
        unique=True
    )
    teacher_id = Column(
        Integer,
        ForeignKey("teachers.id", ondelete="CASCADE"),
        nullable=False,
        index=True
    )
    school_id = Column(
        Integer,
        ForeignKey("schools.id", ondelete="CASCADE"),
        nullable=False,
        index=True
    )

    topic = Column(String(255), nullable=True)
    summary = Column(Text, nullable=False)
    key_insights = Column(JSONB, default=list)
    session_type = Column(String(30), nullable=True)
    message_count = Column(Integer, default=0)

    def __repr__(self) -> str:
        return f"<TeacherChatSessionSummary(session={self.session_id}, topic='{self.topic}')>"


class TeacherMemory(BaseModel):
    """Long-term teacher profile, updated incrementally after conversations."""

    __tablename__ = "teacher_memory"

    teacher_id = Column(
        Integer,
        ForeignKey("teachers.id", ondelete="CASCADE"),
        nullable=False,
        unique=True,
        index=True
    )
    school_id = Column(
        Integer,
        ForeignKey("schools.id", ondelete="CASCADE"),
        nullable=False,
        index=True
    )

    memory_data = Column(JSONB, nullable=False, default=dict)
    extraction_count = Column(Integer, default=0, nullable=False)
    last_session_id = Column(
        Integer,
        ForeignKey("chat_sessions.id", ondelete="SET NULL"),
        nullable=True
    )

    def __repr__(self) -> str:
        return f"<TeacherMemory(teacher={self.teacher_id}, extractions={self.extraction_count})>"
