"""add parent model and parent_students table

Revision ID: 9fe5023de6ad
Revises: 010
Create Date: 2025-11-05 08:25:40.393135

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '9fe5023de6ad'
down_revision: Union[str, None] = '010'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('parents',
    sa.Column('school_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['school_id'], ['schools.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_parents_id'), 'parents', ['id'], unique=False)
    op.create_index(op.f('ix_parents_school_id'), 'parents', ['school_id'], unique=False)
    op.create_index(op.f('ix_parents_user_id'), 'parents', ['user_id'], unique=True)
    op.create_table('parent_students',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('parent_id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['parent_id'], ['parents.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('parent_id', 'student_id', name='uq_parent_student')
    )
    op.drop_index(op.f('ix_adaptive_groups_school_student'), table_name='adaptive_groups')
    op.create_index(op.f('ix_adaptive_groups_id'), 'adaptive_groups', ['id'], unique=False)
    op.drop_index(op.f('ix_analytics_events_school_timestamp'), table_name='analytics_events')
    op.create_index(op.f('ix_analytics_events_id'), 'analytics_events', ['id'], unique=False)
    op.alter_column('assignment_tests', 'order',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('assignment_tests', 'is_deleted',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    op.drop_index(op.f('ix_assignment_tests_is_deleted_created'), table_name='assignment_tests')
    op.create_index(op.f('ix_assignment_tests_assignment_id'), 'assignment_tests', ['assignment_id'], unique=False)
    op.create_index(op.f('ix_assignment_tests_id'), 'assignment_tests', ['id'], unique=False)
    op.create_index(op.f('ix_assignment_tests_test_id'), 'assignment_tests', ['test_id'], unique=False)
    op.alter_column('assignments', 'is_active',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('assignments', 'is_deleted',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    op.create_index(op.f('ix_assignments_id'), 'assignments', ['id'], unique=False)
    op.alter_column('chapters', 'is_deleted',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    op.drop_index(op.f('ix_chapters_is_deleted_created'), table_name='chapters')
    op.create_index(op.f('ix_chapters_id'), 'chapters', ['id'], unique=False)
    op.add_column('learning_activities', sa.Column('activity_metadata', sa.JSON(), nullable=True))
    op.drop_index(op.f('ix_learning_activities_school_timestamp'), table_name='learning_activities')
    op.drop_index(op.f('ix_learning_activities_school_type'), table_name='learning_activities')
    op.create_index(op.f('ix_learning_activities_id'), 'learning_activities', ['id'], unique=False)
    op.create_index(op.f('ix_learning_activities_student_id'), 'learning_activities', ['student_id'], unique=False)
    op.drop_column('learning_activities', 'metadata')
    op.drop_index(op.f('ix_learning_sessions_school_start'), table_name='learning_sessions')
    op.create_index(op.f('ix_learning_sessions_id'), 'learning_sessions', ['id'], unique=False)
    op.alter_column('mastery_history', 'attempts_count',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('mastery_history', 'success_rate',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               server_default=None,
               existing_nullable=False)
    op.drop_index(op.f('ix_mastery_history_school_paragraph'), table_name='mastery_history')
    op.drop_index(op.f('ix_mastery_history_school_student'), table_name='mastery_history')
    op.drop_index(op.f('ix_mastery_history_student_paragraph'), table_name='mastery_history')
    op.create_index(op.f('ix_mastery_history_id'), 'mastery_history', ['id'], unique=False)
    op.alter_column('paragraph_embeddings', 'model',
               existing_type=sa.VARCHAR(length=100),
               server_default=None,
               existing_nullable=False)
    op.alter_column('paragraph_embeddings', 'is_deleted',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    op.drop_index(op.f('ix_paragraph_embeddings_is_deleted_created'), table_name='paragraph_embeddings')
    op.drop_index(op.f('ix_paragraph_embeddings_paragraph_chunk'), table_name='paragraph_embeddings')
    op.create_index(op.f('ix_paragraph_embeddings_id'), 'paragraph_embeddings', ['id'], unique=False)
    op.alter_column('paragraphs', 'is_deleted',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    op.drop_index(op.f('ix_paragraphs_is_deleted_created'), table_name='paragraphs')
    op.create_index(op.f('ix_paragraphs_id'), 'paragraphs', ['id'], unique=False)
    op.alter_column('question_options', 'is_correct',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('question_options', 'is_deleted',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    op.drop_index(op.f('ix_question_options_is_deleted_created'), table_name='question_options')
    op.create_index(op.f('ix_question_options_id'), 'question_options', ['id'], unique=False)
    op.alter_column('questions', 'points',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               server_default=None,
               existing_nullable=False)
    op.alter_column('questions', 'is_deleted',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    op.drop_index(op.f('ix_questions_is_deleted_created'), table_name='questions')
    op.create_index(op.f('ix_questions_id'), 'questions', ['id'], unique=False)
    op.alter_column('school_classes', 'is_deleted',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    op.drop_index(op.f('ix_school_classes_is_deleted_created'), table_name='school_classes')
    op.create_index(op.f('ix_school_classes_id'), 'school_classes', ['id'], unique=False)
    op.alter_column('schools', 'is_active',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('schools', 'is_deleted',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    op.drop_index(op.f('ix_schools_is_deleted_created'), table_name='schools')
    op.drop_constraint(op.f('schools_code_key'), 'schools', type_='unique')
    op.drop_index(op.f('ix_schools_code'), table_name='schools')
    op.create_index(op.f('ix_schools_code'), 'schools', ['code'], unique=True)
    op.create_index(op.f('ix_schools_id'), 'schools', ['id'], unique=False)
    op.alter_column('student_assignments', 'status',
               existing_type=postgresql.ENUM('not_started', 'in_progress', 'completed', 'overdue', name='assignmentstatus'),
               server_default=None,
               existing_nullable=False)
    op.alter_column('student_assignments', 'progress_percentage',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('student_assignments', 'is_deleted',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    op.drop_index(op.f('ix_student_assignments_student_status'), table_name='student_assignments')
    op.create_index(op.f('ix_student_assignments_id'), 'student_assignments', ['id'], unique=False)
    op.alter_column('student_paragraphs', 'is_completed',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('student_paragraphs', 'time_spent',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False)
    op.drop_index(op.f('ix_student_paragraphs_school_student'), table_name='student_paragraphs')
    op.create_index(op.f('ix_student_paragraphs_id'), 'student_paragraphs', ['id'], unique=False)
    op.alter_column('students', 'is_deleted',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    op.drop_index(op.f('ix_students_is_deleted_created'), table_name='students')
    op.drop_constraint(op.f('students_user_id_key'), 'students', type_='unique')
    op.drop_index(op.f('ix_students_user_id'), table_name='students')
    op.create_index(op.f('ix_students_user_id'), 'students', ['user_id'], unique=True)
    op.create_index(op.f('ix_students_id'), 'students', ['id'], unique=False)
    op.alter_column('sync_queue', 'status',
               existing_type=postgresql.ENUM('pending', 'syncing', 'completed', 'failed', name='syncstatus'),
               server_default=None,
               existing_nullable=False)
    op.alter_column('sync_queue', 'attempts',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False)
    op.drop_index(op.f('ix_sync_queue_school_status'), table_name='sync_queue')
    op.create_index(op.f('ix_sync_queue_id'), 'sync_queue', ['id'], unique=False)
    op.alter_column('system_settings', 'is_public',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    op.drop_constraint(op.f('system_settings_key_key'), 'system_settings', type_='unique')
    op.drop_index(op.f('ix_system_settings_key'), table_name='system_settings')
    op.create_index(op.f('ix_system_settings_key'), 'system_settings', ['key'], unique=True)
    op.create_index(op.f('ix_system_settings_id'), 'system_settings', ['id'], unique=False)
    op.alter_column('teachers', 'is_deleted',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    op.drop_index(op.f('ix_teachers_is_deleted_created'), table_name='teachers')
    op.drop_constraint(op.f('teachers_user_id_key'), 'teachers', type_='unique')
    op.drop_index(op.f('ix_teachers_user_id'), table_name='teachers')
    op.create_index(op.f('ix_teachers_user_id'), 'teachers', ['user_id'], unique=True)
    op.create_index(op.f('ix_teachers_id'), 'teachers', ['id'], unique=False)
    op.create_index(op.f('ix_test_attempt_answers_id'), 'test_attempt_answers', ['id'], unique=False)
    op.alter_column('test_attempts', 'attempt_number',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('test_attempts', 'status',
               existing_type=postgresql.ENUM('in_progress', 'completed', 'abandoned', name='attemptstatus'),
               server_default=None,
               existing_nullable=False)
    op.drop_index(op.f('ix_test_attempts_school_created'), table_name='test_attempts')
    op.drop_index(op.f('ix_test_attempts_school_student'), table_name='test_attempts')
    op.drop_index(op.f('ix_test_attempts_student_created'), table_name='test_attempts')
    op.create_index(op.f('ix_test_attempts_id'), 'test_attempts', ['id'], unique=False)
    op.alter_column('tests', 'school_id',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='NULL = global test, NOT NULL = school-specific test',
               existing_nullable=True)
    op.alter_column('tests', 'difficulty',
               existing_type=postgresql.ENUM('easy', 'medium', 'hard', name='difficultylevel'),
               server_default=None,
               existing_nullable=False)
    op.alter_column('tests', 'passing_score',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               server_default=None,
               existing_nullable=False)
    op.alter_column('tests', 'is_active',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('tests', 'is_deleted',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    op.drop_index(op.f('ix_tests_is_deleted_created'), table_name='tests')
    op.create_index(op.f('ix_tests_id'), 'tests', ['id'], unique=False)
    op.alter_column('textbooks', 'school_id',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='NULL = global textbook, NOT NULL = school-specific textbook',
               existing_nullable=True)
    op.alter_column('textbooks', 'global_textbook_id',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='Reference to global textbook if this is a customized version',
               existing_nullable=True)
    op.alter_column('textbooks', 'is_customized',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               comment=None,
               existing_comment='true if school has modified the content from global version',
               existing_nullable=False)
    op.alter_column('textbooks', 'is_active',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('textbooks', 'is_deleted',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    op.drop_index(op.f('ix_textbooks_is_deleted_created'), table_name='textbooks')
    op.drop_index(op.f('ix_textbooks_school_global'), table_name='textbooks')
    op.create_index(op.f('ix_textbooks_id'), 'textbooks', ['id'], unique=False)
    op.alter_column('users', 'is_active',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('users', 'is_verified',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('users', 'is_deleted',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    op.drop_index(op.f('ix_users_is_deleted_created'), table_name='users')
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.create_index(op.f('ix_users_is_deleted_created'), 'users', ['is_deleted', 'created_at'], unique=False)
    op.alter_column('users', 'is_deleted',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               existing_nullable=False)
    op.alter_column('users', 'is_verified',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               existing_nullable=False)
    op.alter_column('users', 'is_active',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('true'),
               existing_nullable=False)
    op.drop_index(op.f('ix_textbooks_id'), table_name='textbooks')
    op.create_index(op.f('ix_textbooks_school_global'), 'textbooks', ['school_id', 'global_textbook_id'], unique=False)
    op.create_index(op.f('ix_textbooks_is_deleted_created'), 'textbooks', ['is_deleted', 'created_at'], unique=False)
    op.alter_column('textbooks', 'is_deleted',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               existing_nullable=False)
    op.alter_column('textbooks', 'is_active',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('true'),
               existing_nullable=False)
    op.alter_column('textbooks', 'is_customized',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               comment='true if school has modified the content from global version',
               existing_nullable=False)
    op.alter_column('textbooks', 'global_textbook_id',
               existing_type=sa.INTEGER(),
               comment='Reference to global textbook if this is a customized version',
               existing_nullable=True)
    op.alter_column('textbooks', 'school_id',
               existing_type=sa.INTEGER(),
               comment='NULL = global textbook, NOT NULL = school-specific textbook',
               existing_nullable=True)
    op.drop_index(op.f('ix_tests_id'), table_name='tests')
    op.create_index(op.f('ix_tests_is_deleted_created'), 'tests', ['is_deleted', 'created_at'], unique=False)
    op.alter_column('tests', 'is_deleted',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               existing_nullable=False)
    op.alter_column('tests', 'is_active',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('true'),
               existing_nullable=False)
    op.alter_column('tests', 'passing_score',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               server_default=sa.text('0.7'),
               existing_nullable=False)
    op.alter_column('tests', 'difficulty',
               existing_type=postgresql.ENUM('easy', 'medium', 'hard', name='difficultylevel'),
               server_default=sa.text("'medium'::difficultylevel"),
               existing_nullable=False)
    op.alter_column('tests', 'school_id',
               existing_type=sa.INTEGER(),
               comment='NULL = global test, NOT NULL = school-specific test',
               existing_nullable=True)
    op.drop_index(op.f('ix_test_attempts_id'), table_name='test_attempts')
    op.create_index(op.f('ix_test_attempts_student_created'), 'test_attempts', ['student_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_test_attempts_school_student'), 'test_attempts', ['school_id', 'student_id'], unique=False)
    op.create_index(op.f('ix_test_attempts_school_created'), 'test_attempts', ['school_id', 'created_at'], unique=False)
    op.alter_column('test_attempts', 'status',
               existing_type=postgresql.ENUM('in_progress', 'completed', 'abandoned', name='attemptstatus'),
               server_default=sa.text("'in_progress'::attemptstatus"),
               existing_nullable=False)
    op.alter_column('test_attempts', 'attempt_number',
               existing_type=sa.INTEGER(),
               server_default=sa.text('1'),
               existing_nullable=False)
    op.drop_index(op.f('ix_test_attempt_answers_id'), table_name='test_attempt_answers')
    op.drop_index(op.f('ix_teachers_id'), table_name='teachers')
    op.drop_index(op.f('ix_teachers_user_id'), table_name='teachers')
    op.create_index(op.f('ix_teachers_user_id'), 'teachers', ['user_id'], unique=False)
    op.create_unique_constraint(op.f('teachers_user_id_key'), 'teachers', ['user_id'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('ix_teachers_is_deleted_created'), 'teachers', ['is_deleted', 'created_at'], unique=False)
    op.alter_column('teachers', 'is_deleted',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               existing_nullable=False)
    op.drop_index(op.f('ix_system_settings_id'), table_name='system_settings')
    op.drop_index(op.f('ix_system_settings_key'), table_name='system_settings')
    op.create_index(op.f('ix_system_settings_key'), 'system_settings', ['key'], unique=False)
    op.create_unique_constraint(op.f('system_settings_key_key'), 'system_settings', ['key'], postgresql_nulls_not_distinct=False)
    op.alter_column('system_settings', 'is_public',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               existing_nullable=False)
    op.drop_index(op.f('ix_sync_queue_id'), table_name='sync_queue')
    op.create_index(op.f('ix_sync_queue_school_status'), 'sync_queue', ['school_id', 'status'], unique=False)
    op.alter_column('sync_queue', 'attempts',
               existing_type=sa.INTEGER(),
               server_default=sa.text('0'),
               existing_nullable=False)
    op.alter_column('sync_queue', 'status',
               existing_type=postgresql.ENUM('pending', 'syncing', 'completed', 'failed', name='syncstatus'),
               server_default=sa.text("'pending'::syncstatus"),
               existing_nullable=False)
    op.drop_index(op.f('ix_students_id'), table_name='students')
    op.drop_index(op.f('ix_students_user_id'), table_name='students')
    op.create_index(op.f('ix_students_user_id'), 'students', ['user_id'], unique=False)
    op.create_unique_constraint(op.f('students_user_id_key'), 'students', ['user_id'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('ix_students_is_deleted_created'), 'students', ['is_deleted', 'created_at'], unique=False)
    op.alter_column('students', 'is_deleted',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               existing_nullable=False)
    op.drop_index(op.f('ix_student_paragraphs_id'), table_name='student_paragraphs')
    op.create_index(op.f('ix_student_paragraphs_school_student'), 'student_paragraphs', ['school_id', 'student_id'], unique=False)
    op.alter_column('student_paragraphs', 'time_spent',
               existing_type=sa.INTEGER(),
               server_default=sa.text('0'),
               existing_nullable=False)
    op.alter_column('student_paragraphs', 'is_completed',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               existing_nullable=False)
    op.drop_index(op.f('ix_student_assignments_id'), table_name='student_assignments')
    op.create_index(op.f('ix_student_assignments_student_status'), 'student_assignments', ['student_id', 'status'], unique=False)
    op.alter_column('student_assignments', 'is_deleted',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               existing_nullable=False)
    op.alter_column('student_assignments', 'progress_percentage',
               existing_type=sa.INTEGER(),
               server_default=sa.text('0'),
               existing_nullable=False)
    op.alter_column('student_assignments', 'status',
               existing_type=postgresql.ENUM('not_started', 'in_progress', 'completed', 'overdue', name='assignmentstatus'),
               server_default=sa.text("'not_started'::assignmentstatus"),
               existing_nullable=False)
    op.drop_index(op.f('ix_schools_id'), table_name='schools')
    op.drop_index(op.f('ix_schools_code'), table_name='schools')
    op.create_index(op.f('ix_schools_code'), 'schools', ['code'], unique=False)
    op.create_unique_constraint(op.f('schools_code_key'), 'schools', ['code'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('ix_schools_is_deleted_created'), 'schools', ['is_deleted', 'created_at'], unique=False)
    op.alter_column('schools', 'is_deleted',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               existing_nullable=False)
    op.alter_column('schools', 'is_active',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('true'),
               existing_nullable=False)
    op.drop_index(op.f('ix_school_classes_id'), table_name='school_classes')
    op.create_index(op.f('ix_school_classes_is_deleted_created'), 'school_classes', ['is_deleted', 'created_at'], unique=False)
    op.alter_column('school_classes', 'is_deleted',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               existing_nullable=False)
    op.drop_index(op.f('ix_questions_id'), table_name='questions')
    op.create_index(op.f('ix_questions_is_deleted_created'), 'questions', ['is_deleted', 'created_at'], unique=False)
    op.alter_column('questions', 'is_deleted',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               existing_nullable=False)
    op.alter_column('questions', 'points',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               server_default=sa.text('1.0'),
               existing_nullable=False)
    op.drop_index(op.f('ix_question_options_id'), table_name='question_options')
    op.create_index(op.f('ix_question_options_is_deleted_created'), 'question_options', ['is_deleted', 'created_at'], unique=False)
    op.alter_column('question_options', 'is_deleted',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               existing_nullable=False)
    op.alter_column('question_options', 'is_correct',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               existing_nullable=False)
    op.drop_index(op.f('ix_paragraphs_id'), table_name='paragraphs')
    op.create_index(op.f('ix_paragraphs_is_deleted_created'), 'paragraphs', ['is_deleted', 'created_at'], unique=False)
    op.alter_column('paragraphs', 'is_deleted',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               existing_nullable=False)
    op.drop_index(op.f('ix_paragraph_embeddings_id'), table_name='paragraph_embeddings')
    op.create_index(op.f('ix_paragraph_embeddings_paragraph_chunk'), 'paragraph_embeddings', ['paragraph_id', 'chunk_index'], unique=False)
    op.create_index(op.f('ix_paragraph_embeddings_is_deleted_created'), 'paragraph_embeddings', ['is_deleted', 'created_at'], unique=False)
    op.alter_column('paragraph_embeddings', 'is_deleted',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               existing_nullable=False)
    op.alter_column('paragraph_embeddings', 'model',
               existing_type=sa.VARCHAR(length=100),
               server_default=sa.text("'text-embedding-3-small'::character varying"),
               existing_nullable=False)
    op.drop_index(op.f('ix_mastery_history_id'), table_name='mastery_history')
    op.create_index(op.f('ix_mastery_history_student_paragraph'), 'mastery_history', ['student_id', 'paragraph_id'], unique=False)
    op.create_index(op.f('ix_mastery_history_school_student'), 'mastery_history', ['school_id', 'student_id'], unique=False)
    op.create_index(op.f('ix_mastery_history_school_paragraph'), 'mastery_history', ['school_id', 'paragraph_id'], unique=False)
    op.alter_column('mastery_history', 'success_rate',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               server_default=sa.text('0.0'),
               existing_nullable=False)
    op.alter_column('mastery_history', 'attempts_count',
               existing_type=sa.INTEGER(),
               server_default=sa.text('0'),
               existing_nullable=False)
    op.drop_index(op.f('ix_learning_sessions_id'), table_name='learning_sessions')
    op.create_index(op.f('ix_learning_sessions_school_start'), 'learning_sessions', ['school_id', 'session_start'], unique=False)
    op.add_column('learning_activities', sa.Column('metadata', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_learning_activities_student_id'), table_name='learning_activities')
    op.drop_index(op.f('ix_learning_activities_id'), table_name='learning_activities')
    op.create_index(op.f('ix_learning_activities_school_type'), 'learning_activities', ['school_id', 'activity_type'], unique=False)
    op.create_index(op.f('ix_learning_activities_school_timestamp'), 'learning_activities', ['school_id', 'activity_timestamp'], unique=False)
    op.drop_column('learning_activities', 'activity_metadata')
    op.drop_index(op.f('ix_chapters_id'), table_name='chapters')
    op.create_index(op.f('ix_chapters_is_deleted_created'), 'chapters', ['is_deleted', 'created_at'], unique=False)
    op.alter_column('chapters', 'is_deleted',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               existing_nullable=False)
    op.drop_index(op.f('ix_assignments_id'), table_name='assignments')
    op.alter_column('assignments', 'is_deleted',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               existing_nullable=False)
    op.alter_column('assignments', 'is_active',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('true'),
               existing_nullable=False)
    op.drop_index(op.f('ix_assignment_tests_test_id'), table_name='assignment_tests')
    op.drop_index(op.f('ix_assignment_tests_id'), table_name='assignment_tests')
    op.drop_index(op.f('ix_assignment_tests_assignment_id'), table_name='assignment_tests')
    op.create_index(op.f('ix_assignment_tests_is_deleted_created'), 'assignment_tests', ['is_deleted', 'created_at'], unique=False)
    op.alter_column('assignment_tests', 'is_deleted',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               existing_nullable=False)
    op.alter_column('assignment_tests', 'order',
               existing_type=sa.INTEGER(),
               server_default=sa.text('0'),
               existing_nullable=False)
    op.drop_index(op.f('ix_analytics_events_id'), table_name='analytics_events')
    op.create_index(op.f('ix_analytics_events_school_timestamp'), 'analytics_events', ['school_id', 'event_timestamp'], unique=False)
    op.drop_index(op.f('ix_adaptive_groups_id'), table_name='adaptive_groups')
    op.create_index(op.f('ix_adaptive_groups_school_student'), 'adaptive_groups', ['school_id', 'student_id'], unique=False)
    op.drop_table('parent_students')
    op.drop_index(op.f('ix_parents_user_id'), table_name='parents')
    op.drop_index(op.f('ix_parents_school_id'), table_name='parents')
    op.drop_index(op.f('ix_parents_id'), table_name='parents')
    op.drop_table('parents')
    # ### end Alembic commands ###
