export * from './school';
export * from './textbook';
export * from './test';
// School Admin validations
export * from './student';
export * from './teacher';
export * from './parent';
export * from './class';
export * from './settings';
